# application.yml

spring:
  datasource:
    url: jdbc:mysql:///mysqlstudy?useSSL=false&useOldAliasMetadataBehavior=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

upload:
  path: /doc/upload/path

server:
  port: 10001

servlet:
  multipart:
    max-request-size: 10MB
    max-file-size: 5MB

security:
  password:
    encoder: bcrypt